version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: todo_db         
      POSTGRES_USER: user          
      POSTGRES_PASSWORD: password   
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./helper/init.sql:/docker-entrypoint-initdb.d/init.sql  # Koppeling naar het initialisatie script
    ports:
      - "5432:5432" 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  postgres_data:
